const express = require('express')
const Paymodes = require('../models/paymode')
const router = express.Router()

router.get('/paymode', async function (req, res) {

    res.send({
        "paymodes": [
            {
                "id": 1,
                "recid": 1,
                "subdomain_id": "01",
                "pay_name": "Cash",
                "paytype": "1",
                "account": "1020",
                "isforsystem": "0",
                "priority": "0",
                "addedby": "1",
                "addedon": "2001-01-01",
                "updatedby": "0",
                "updatedon": "2001-01-01",
                "deletedby": "0",
                "deletedon": "2001-01-01"
            },
            {
                "id": 2,
                "recid": 2,
                "subdomain_id": "01",
                "pay_name": "POS Sterling",
                "paytype": "1",
                "account": "1060",
                "isforsystem": "0",
                "priority": "0",
                "addedby": "1",
                "addedon": "2001-01-01",
                "updatedby": "0",
                "updatedon": "2001-01-01",
                "deletedby": "0",
                "deletedon": "2001-01-01"
            },
            {
                "id": 3,
                "recid": 3,
                "subdomain_id": "01",
                "pay_name": "POS GTB",
                "paytype": "1",
                "account": "1075",
                "isforsystem": "0",
                "priority": "0",
                "addedby": "1",
                "addedon": "2021-03-19",
                "updatedby": "0",
                "updatedon": "2001-01-01",
                "deletedby": "0",
                "deletedon": "2001-01-01"
            },
            {
                "id": 4,
                "recid": 4,
                "subdomain_id": "01",
                "pay_name": "GT TRF",
                "paytype": "1",
                "account": "1075",
                "isforsystem": "0",
                "priority": "0",
                "addedby": "127",
                "addedon": "2021-03-31",
                "updatedby": "0",
                "updatedon": "2001-01-01",
                "deletedby": "0",
                "deletedon": "2001-01-01"
            },
            {
                "id": 5,
                "recid": 5,
                "subdomain_id": "01",
                "pay_name": "Sterling TRF",
                "paytype": "1",
                "account": "1060",
                "isforsystem": "0",
                "priority": "0",
                "addedby": "127",
                "addedon": "2021-03-31",
                "updatedby": "0",
                "updatedon": "2001-01-01",
                "deletedby": "0",
                "deletedon": "2001-01-01"
            },
            {
                "id": 6,
                "recid": 6,
                "subdomain_id": "02",
                "pay_name": "Cash",
                "paytype": "1",
                "account": "1020",
                "isforsystem": "0",
                "priority": "0",
                "addedby": "179963",
                "addedon": "2021-05-13",
                "updatedby": "0",
                "updatedon": "2001-01-01",
                "deletedby": "0",
                "deletedon": "2001-01-01"
            },
            {
                "id": 7,
                "recid": 7,
                "subdomain_id": "02",
                "pay_name": "Transfer",
                "paytype": "1",
                "account": "1070",
                "isforsystem": "0",
                "priority": "0",
                "addedby": "179963",
                "addedon": "2021-05-13",
                "updatedby": "0",
                "updatedon": "2001-01-01",
                "deletedby": "0",
                "deletedon": "2001-01-01"
            },
            {
                "id": 8,
                "recid": 8,
                "subdomain_id": "03",
                "pay_name": "Cash",
                "paytype": "1",
                "account": "1020",
                "isforsystem": "0",
                "priority": "0",
                "addedby": "584610",
                "addedon": "2021-07-29",
                "updatedby": "0",
                "updatedon": "2001-01-01",
                "deletedby": "0",
                "deletedon": "2001-01-01"
            },
            {
                "id": 9,
                "recid": 9,
                "subdomain_id": "03",
                "pay_name": "GT Bank",
                "paytype": "1",
                "account": "1075",
                "isforsystem": "0",
                "priority": "0",
                "addedby": "584610",
                "addedon": "2021-08-01",
                "updatedby": "0",
                "updatedon": "2001-01-01",
                "deletedby": "0",
                "deletedon": "2001-01-01"
            },
            {
                "id": 10,
                "recid": 10,
                "subdomain_id": "03",
                "pay_name": "First Bank",
                "paytype": "1",
                "account": "1070",
                "isforsystem": "0",
                "priority": "0",
                "addedby": "584610",
                "addedon": "2021-08-06",
                "updatedby": "0",
                "updatedon": "2001-01-01",
                "deletedby": "0",
                "deletedon": "2001-01-01"
            },
            {
                "id": 11,
                "recid": 11,
                "subdomain_id": "03",
                "pay_name": "Zenith Bank",
                "paytype": "1",
                "account": "1065",
                "isforsystem": "0",
                "priority": "0",
                "addedby": "584610",
                "addedon": "2021-08-06",
                "updatedby": "0",
                "updatedon": "2001-01-01",
                "deletedby": "0",
                "deletedon": "2001-01-01"
            },
            {
                "id": 12,
                "recid": 12,
                "subdomain_id": "03",
                "pay_name": "Access Bank",
                "paytype": "1",
                "account": "1060",
                "isforsystem": "0",
                "priority": "0",
                "addedby": "584610",
                "addedon": "2021-08-06",
                "updatedby": "0",
                "updatedon": "2001-01-01",
                "deletedby": "0",
                "deletedon": "2001-01-01"
            },
            {
                "id": 13,
                "recid": 13,
                "subdomain_id": "04",
                "pay_name": "Cash",
                "paytype": "1",
                "account": "1020",
                "isforsystem": "0",
                "priority": "0",
                "addedby": "2",
                "addedon": "2021-08-27",
                "updatedby": "0",
                "updatedon": "2001-01-01",
                "deletedby": "0",
                "deletedon": "2001-01-01"
            },
            {
                "id": 14,
                "recid": 14,
                "subdomain_id": "05",
                "pay_name": "Cash",
                "paytype": "1",
                "account": "1020",
                "isforsystem": "0",
                "priority": "0",
                "addedby": "2",
                "addedon": "2021-09-03",
                "updatedby": "0",
                "updatedon": "2001-01-01",
                "deletedby": "0",
                "deletedon": "2001-01-01"
            },
            {
                "id": 15,
                "recid": 15,
                "subdomain_id": "05",
                "pay_name": "TRF FCMB",
                "paytype": "1",
                "account": "1060",
                "isforsystem": "0",
                "priority": "0",
                "addedby": "2",
                "addedon": "2021-09-03",
                "updatedby": "0",
                "updatedon": "2001-01-01",
                "deletedby": "0",
                "deletedon": "2001-01-01"
            },
            {
                "id": 16,
                "recid": 16,
                "subdomain_id": "04",
                "pay_name": "BANK TRANSFER",
                "paytype": "1",
                "account": "1030",
                "isforsystem": "0",
                "priority": "0",
                "addedby": "553363",
                "addedon": "2021-09-07",
                "updatedby": "0",
                "updatedon": "2001-01-01",
                "deletedby": "0",
                "deletedon": "2001-01-01"
            },
            {
                "id": 17,
                "recid": 17,
                "subdomain_id": "06",
                "pay_name": "Cash",
                "paytype": "1",
                "account": "1010",
                "isforsystem": "0",
                "priority": "0",
                "addedby": "2",
                "addedon": "2021-09-26",
                "updatedby": "249354",
                "updatedon": "2021-10-04",
                "deletedby": "0",
                "deletedon": "2001-01-01"
            },
            {
                "id": 18,
                "recid": 18,
                "subdomain_id": "06",
                "pay_name": "FIRST BANK TRANSFER",
                "paytype": "1",
                "account": "1065",
                "isforsystem": "0",
                "priority": "0",
                "addedby": "249354",
                "addedon": "2021-10-05",
                "updatedby": "0",
                "updatedon": "2001-01-01",
                "deletedby": "0",
                "deletedon": "2001-01-01"
            },
            {
                "id": 19,
                "recid": 19,
                "subdomain_id": "06",
                "pay_name": "ACCESS BANK TRANSFER",
                "paytype": "1",
                "account": "1085",
                "isforsystem": "0",
                "priority": "0",
                "addedby": "249354",
                "addedon": "2021-10-05",
                "updatedby": "0",
                "updatedon": "2001-01-01",
                "deletedby": "0",
                "deletedon": "2001-01-01"
            },
            {
                "id": 20,
                "recid": 20,
                "subdomain_id": "06",
                "pay_name": "FIDELITY BANK TRANSFER",
                "paytype": "1",
                "account": "1075",
                "isforsystem": "0",
                "priority": "0",
                "addedby": "249354",
                "addedon": "2021-10-05",
                "updatedby": "0",
                "updatedon": "2001-01-01",
                "deletedby": "0",
                "deletedon": "2001-01-01"
            },
            {
                "id": 21,
                "recid": 21,
                "subdomain_id": "06",
                "pay_name": "ECO BANK TRANSFER",
                "paytype": "1",
                "account": "1080",
                "isforsystem": "0",
                "priority": "0",
                "addedby": "249354",
                "addedon": "2021-10-05",
                "updatedby": "0",
                "updatedon": "2001-01-01",
                "deletedby": "0",
                "deletedon": "2001-01-01"
            },
            {
                "id": 22,
                "recid": 22,
                "subdomain_id": "06",
                "pay_name": "UBA BANK TRANSFER",
                "paytype": "1",
                "account": "1090",
                "isforsystem": "0",
                "priority": "0",
                "addedby": "249354",
                "addedon": "2021-10-05",
                "updatedby": "0",
                "updatedon": "2001-01-01",
                "deletedby": "0",
                "deletedon": "2001-01-01"
            },
            {
                "id": 23,
                "recid": 23,
                "subdomain_id": "06",
                "pay_name": "ZENITH BANK TRANFER",
                "paytype": "1",
                "account": "1070",
                "isforsystem": "0",
                "priority": "0",
                "addedby": "249354",
                "addedon": "2021-10-05",
                "updatedby": "0",
                "updatedon": "2001-01-01",
                "deletedby": "0",
                "deletedon": "2001-01-01"
            },
            {
                "id": 24,
                "recid": 24,
                "subdomain_id": "06",
                "pay_name": "KEYSTONE BANK TRANSFER",
                "paytype": "1",
                "account": "1095",
                "isforsystem": "0",
                "priority": "0",
                "addedby": "249354",
                "addedon": "2021-10-05",
                "updatedby": "0",
                "updatedon": "2001-01-01",
                "deletedby": "0",
                "deletedon": "2001-01-01"
            },
            {
                "id": 25,
                "recid": 25,
                "subdomain_id": "07",
                "pay_name": "Cash",
                "paytype": "1",
                "account": "0000",
                "isforsystem": "0",
                "priority": "0",
                "addedby": "2",
                "addedon": "2021-10-14",
                "updatedby": "0",
                "updatedon": "2001-01-01",
                "deletedby": "0",
                "deletedon": "2001-01-01"
            }
        ]
    })
})

module.exports = router
